// <auto-generated />
using System;
using DAL.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ba27383-5595-46bb-a4c7-0bf1393004a8"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1388),
                            IsDeleted = false,
                            Name = "Aksiyon"
                        },
                        new
                        {
                            Id = new Guid("517fdb38-4526-4136-b04e-f44da166eb0d"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1391),
                            IsDeleted = false,
                            Name = "Animasyon"
                        },
                        new
                        {
                            Id = new Guid("9ee74f9e-e752-4876-92a6-7612faa21125"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1393),
                            IsDeleted = false,
                            Name = "Belgesel"
                        },
                        new
                        {
                            Id = new Guid("073d0718-7198-495e-8bfc-282b3f312b87"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1395),
                            IsDeleted = false,
                            Name = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = new Guid("62d09be1-7149-4323-91b8-920f0e73b994"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1397),
                            IsDeleted = false,
                            Name = "Biyografi"
                        },
                        new
                        {
                            Id = new Guid("96f76275-6eae-4f1d-a779-e2081708dbaf"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1401),
                            IsDeleted = false,
                            Name = "Dram"
                        },
                        new
                        {
                            Id = new Guid("0fe82780-5694-4810-8109-b2d81997b828"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1403),
                            IsDeleted = false,
                            Name = "Fantastik"
                        },
                        new
                        {
                            Id = new Guid("2fbe1558-2569-4a46-8c9a-2ee757fb1573"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1406),
                            IsDeleted = false,
                            Name = "Gerilim"
                        },
                        new
                        {
                            Id = new Guid("6f91d7ca-cc5a-47cd-9b19-58806496f045"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1408),
                            IsDeleted = false,
                            Name = "Gizem"
                        },
                        new
                        {
                            Id = new Guid("1370f594-9ef7-4cc5-95b7-2380b4c9b2d9"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1410),
                            IsDeleted = false,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = new Guid("12367738-4c57-4874-a1b6-eebccfe9aba8"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1412),
                            IsDeleted = false,
                            Name = "Korku"
                        },
                        new
                        {
                            Id = new Guid("1b01fc9e-ef99-43aa-8557-d70897d141dd"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1414),
                            IsDeleted = false,
                            Name = "Macera"
                        },
                        new
                        {
                            Id = new Guid("12f37527-8d1b-4a9b-8ec9-77cbd37bb086"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1416),
                            IsDeleted = false,
                            Name = "Müzik"
                        },
                        new
                        {
                            Id = new Guid("6d0f565d-d05a-45d2-9475-f8d1f6ad1cd5"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1421),
                            IsDeleted = false,
                            Name = "Polisiye"
                        },
                        new
                        {
                            Id = new Guid("0f38e399-7019-4624-b05a-1a84a18e1d81"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1424),
                            IsDeleted = false,
                            Name = "Reality"
                        },
                        new
                        {
                            Id = new Guid("d2dbfcc0-a9f5-4008-8613-9f4f5086307d"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1426),
                            IsDeleted = false,
                            Name = "Romantik"
                        },
                        new
                        {
                            Id = new Guid("c7571c9a-a959-47d8-b3ea-ded35bb1ca91"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1428),
                            IsDeleted = false,
                            Name = "Savaş"
                        },
                        new
                        {
                            Id = new Guid("d5b3a8c5-f8dc-4495-b90f-d41ea9985878"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = new Guid("541626c9-d0d2-491b-a8a8-adde6198b7cd"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1432),
                            IsDeleted = false,
                            Name = "Kısa Film"
                        },
                        new
                        {
                            Id = new Guid("d1eec22c-a829-41be-be4b-5a2c15dbc4ab"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1434),
                            IsDeleted = false,
                            Name = "Spor"
                        },
                        new
                        {
                            Id = new Guid("4ab0190f-a4d4-49e8-8ac3-718481aa2a89"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1436),
                            IsDeleted = false,
                            Name = "Suç"
                        },
                        new
                        {
                            Id = new Guid("91f14291-3c71-44da-8a4e-ca44f7a82c76"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1439),
                            IsDeleted = false,
                            Name = "StandUp"
                        },
                        new
                        {
                            Id = new Guid("ed6396fd-4fe3-4b75-b585-d10b933a4c51"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1441),
                            IsDeleted = false,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = new Guid("f88e8486-c147-44bc-8c98-a5bd9ae98d86"),
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1443),
                            IsDeleted = false,
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ImdbRating")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoviePosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6ec2a92-e085-4fbc-abb4-a62038867165"),
                            Cast = "Tim Robbins, Morgan Freeman",
                            CategoryId = new Guid("96f76275-6eae-4f1d-a779-e2081708dbaf"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1219),
                            Description = "Andy Dufresne, haksız yere hüküm giydiği Shawshank hapishanesinde yaşamını sürdürmeye çalışırken, dostluğun ve umudun gücünü keşfeder.",
                            Director = "Frank Darabont",
                            ImdbRating = 9.3000000000000007,
                            IsDeleted = false,
                            MovieDuration = "2 saat 22 dakika",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
                            MovieTrailerUrl = "https://youtu.be/PLl99DlL6b4",
                            Name = "The Shawshank Redemption",
                            ProductionYear = "1994"
                        },
                        new
                        {
                            Id = new Guid("320b4694-9dd1-432f-9cac-c0bf193ef68f"),
                            Cast = "Edward Norton, Brad Pitt",
                            CategoryId = new Guid("96f76275-6eae-4f1d-a779-e2081708dbaf"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1249),
                            Description = "Sıradan bir ofis çalışanı, karizmatik bir yabancıyla tanışarak hayatını değiştiren bir yeraltı dövüş kulübünü kurar.",
                            Director = "David Fincher",
                            ImdbRating = 8.8000000000000007,
                            IsDeleted = false,
                            MovieDuration = "2 saat 19 dakika",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BODQ0OWJiMzktYjNlYi00MzcwLThlZWMtMzRkYTY4ZDgxNzgxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            MovieTrailerUrl = "https://youtu.be/BdJKm16Co6M",
                            Name = "Fight Club",
                            ProductionYear = "1999"
                        },
                        new
                        {
                            Id = new Guid("46747148-7742-49d3-bc47-7b64dcfdefad"),
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt",
                            CategoryId = new Guid("d5b3a8c5-f8dc-4495-b90f-d41ea9985878"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1252),
                            Description = "Dom Cobb, insanların rüyalarına girme yeteneği olan bir hırsızdır. Tehlikeli bir iş teklifi alır ve zihin çalma sanatını kullanarak karmaşık bir soygun planlar.",
                            Director = "Christopher Nolan",
                            ImdbRating = 8.8000000000000007,
                            IsDeleted = false,
                            MovieDuration = "2 saat 28 dakika",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            MovieTrailerUrl = "https://youtu.be/YoHD9XEInc0",
                            Name = "Inception",
                            ProductionYear = "2010"
                        },
                        new
                        {
                            Id = new Guid("18fa548f-94e5-4a8c-bd07-65c7ba61cd2e"),
                            Cast = "Matthew McConaughey, Anne Hathaway",
                            CategoryId = new Guid("d5b3a8c5-f8dc-4495-b90f-d41ea9985878"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1271),
                            Description = "Yakın bir gelecekte, dünya yaşanmaz hale gelmiştir. Cooper adlı astronot, yeni bir yaşanabilir gezegen arayışına çıkar ve zaman ile uzay arasındaki sırları keşfeder.",
                            Director = "Christopher Nolan",
                            ImdbRating = 8.5999999999999996,
                            IsDeleted = false,
                            MovieDuration = "2 saat 49 dakika",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            MovieTrailerUrl = "https://youtu.be/zSWdZVtXT7E",
                            Name = "Interstellar",
                            ProductionYear = "2014"
                        },
                        new
                        {
                            Id = new Guid("c2ac8ca6-0f24-4553-b4b0-11176cada194"),
                            Cast = "Leonardo DiCaprio, Jonah Hill",
                            CategoryId = new Guid("4ab0190f-a4d4-49e8-8ac3-718481aa2a89"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1273),
                            Description = "Jordan Belfort, finans dünyasının en ünlü dolandırıcısıdır. Zenginlik ve lüksün doruklarına tırmanırken yasadışı yollarla servet kazanır.",
                            Director = "Martin Scorsese",
                            ImdbRating = 8.1999999999999993,
                            IsDeleted = false,
                            MovieDuration = "3 saat",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_FMjpg_UX1000_.jpg",
                            MovieTrailerUrl = "https://youtu.be/iszwuX1AK6A",
                            Name = "The Wolf of Wall Street",
                            ProductionYear = "2013"
                        },
                        new
                        {
                            Id = new Guid("7644d8bb-e3d9-423e-be5e-fd4c1138d7d0"),
                            Cast = "Cary Elwes, Leigh Whannell",
                            CategoryId = new Guid("12367738-4c57-4874-a1b6-eebccfe9aba8"),
                            Country = "ABD",
                            CreatedDate = new DateTime(2023, 9, 13, 23, 55, 20, 221, DateTimeKind.Local).AddTicks(1278),
                            Description = "Bir dizi karmaşık ve ölümcül oyunlarla dolu bir labirentte uyanan iki yabancı, korkunç bir sırrı çözmeye çalışır.",
                            Director = "James Wan",
                            ImdbRating = 7.5999999999999996,
                            IsDeleted = false,
                            MovieDuration = "1 saat 43 dakika",
                            MoviePosterUrl = "https://m.media-amazon.com/images/M/MV5BM2M1MzI1MWYtYmM2ZC00OWY3LTk0ZGMtNmRkNzU1NzEzMWE5XkEyXkFqcGdeQXVyODUwOTkwODk@._V1_FMjpg_UX1000_.jpg",
                            MovieTrailerUrl = "https://youtu.be/S-1QgOMQ-ls",
                            Name = "Saw",
                            ProductionYear = "2004"
                        });
                });

            modelBuilder.Entity("Entities.Movie", b =>
                {
                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
